Repository JunyDeveloper/GamblingModLethalCompany, pull requests merged in 2024-01, with the labels that each got.

#14 Increase the DEFAULT chance of getting a good roll
  GamblersMod/config/GambleConfigSettingsSerializable.cs
Labels: Release 1.0.9

#29 Update multiplier config to accept decimals
  GamblersMod/GamblingMachine/GamblingMachine.cs
  GamblersMod/config/GambleConfigSettingsSerializable.cs
Labels: bug, Release 1.1.3

#28 Added cooldown as a configurable value
  GamblersMod/Constants/GambleConstants.cs
  GamblersMod/GamblingMachine/GamblingMachine.cs
  GamblersMod/config/GambleConfigNetworkHelper.cs
  GamblersMod/config/GambleConfigSettingsSerializable.cs
  ThunderStore/GamblersMod/README.md
Labels: enhancement, Release 1.1.3

#39 Gambling machine manager state not resetting on player disconnect
  GamblersMod/GamblingMachineManager/GamblingMachineManager.cs
  GamblersMod/Patches/GameNetworkManagerPatch.cs
  GamblersMod/Patches/RoundManagerPatch.cs
  GamblersMod/RoundManagerCustom/RoundManagerCustom.cs
  ThunderStore/GamblersMod/GamblersMod.dll
Labels: bug
